# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26ceadb63b21e6a4c9da719699ab8384108d75fd10475165fceda8a941914ae208023d319adc132d171edbe4a107cf5572f4ccca0c14f4a9106f8d228cd7b65c

test:
  secret_key_base: 1584facbe33b38d279ed8b086dbd0db8f2c28c2e2c2fc1351aa636d1006efbab5c12b1b91fe8472a09a114e16f5c760d9993b1aa3985aa527741f53290bf8c86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
